version: '3.5'

volumes:
  postgres-data:
  redis-data:
networks:
  sportequip-net:

services:
  postgres:
    container_name: sportequip_postgres
    image: postgres:14.0
    env_file: .env
    ports:
      - 5435:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sportequip-net

  redis:
    container_name: sportequip_redis
    image: redis:latest
    entrypoint: redis-server --appendonly yes
    ports:
      - 6385:6379
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - sportequip-net
